### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)

### ISSUE THREAD

**Issue by deralexxx** [MISP/PyTaxonomies#4]
That should work according to the documentation, but it does not.

````
from pytaxonomies import Taxonomies
taxonomies = Taxonomies()
taxonomies.all_machinetags()
Traceback (most recent call last):
  File "/Users/bla/Documents/scripts/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-55b0011c9157>", line 1, in <module>
    taxonomies.all_machinetags()
  File "/Users/bla/Documents/scripts/bla/venv3/lib/python2.7/site-packages/pytaxonomies/api.py", line 328, in all_machinetags
    return [taxonomy.machinetags() for taxonomy in self.values()]
  File "/Users/bla/Documents/scripts/bla/venv3/lib/python2.7/site-packages/pytaxonomies/api.py", line 202, in machinetags
    to_return.append('{}:{}="{}"'.format(self.name, p, k))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
````

**Comment by Rafiot** [comment]
Hmmm... Python version?

**Comment by deralexxx** [comment]
the ... historic ... version

python3 fixed it.

**Comment by Rafiot** [comment]
:p
